import fs from 'fs';
import path from 'path';
import Sequelize from 'sequelize';
import configFactory from '../../config/config.json';

/*
* generated by sequelize.cli
* convert to es6 by virgiawan
* t: @sapi_mabur
*/
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = configFactory[env];
const db = {};

let sequelize = null;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    let model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if(typeof db[modelName].associate === 'function' ){
    db[modelName].associate(db);    
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
